"""Add UserCardProgress table

Revision ID: a7d9f1f87b8b
Revises: ad72ca99131e
Create Date: 2025-09-16 02:31:03.571839

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7d9f1f87b8b'
down_revision = 'ad72ca99131e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_card_progress',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('card_id', sa.Integer(), nullable=False),
    sa.Column('last_response_time_ms', sa.Integer(), nullable=True),
    sa.Column('correct_count', sa.Integer(), nullable=True),
    sa.Column('incorrect_count', sa.Integer(), nullable=True),
    sa.Column('last_seen_at', sa.DateTime(), nullable=True),
    sa.Column('score', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['card_id'], ['card.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('card_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_card_progress')
    # ### end Alembic commands ###
